#############################################################
# 1. gRpc.server Network Listeners                          #
# [Format] ip1:port1, ip2:port2, ..., ipN:portN             #
# [Example] 192.168.1.10:8424, 127.0.0.1:8424, 0.0.0.0:8424 #
#############################################################
gRpc.server.bindings=0.0.0.0:8424, 0.0.0.0:8425
#gRpc.server.autostart=true

# Note: make it prime number when you have both NIO and gRPC server running
#gRpc.server.idle.threshold.second=59

# Note: valid value = String, HostString, HostName, AddressStirng, HostAddress, AddrHostName, CanonicalHostName
#gRpc.server.CallerAddressFilter.option=String

# Note: Whitelist in CSV format, example: 127.0.0.1, 192\\.168\\.1\\.
#gRpc.server.CallerAddressFilter.Whitelist=

# Note: Blacklist in CSV format, example: 10.1.1.40, 192\\.168\\.2\\.
#gRpc.server.CallerAddressFilter.Blacklist=

# Note: valid value = VirtualThread (default for Java 21+), CPU, IO and Mixed (default for old Java)
# Note:  use CPU core + 1 when application is CPU bound
# Note: use CPU core x 2 + 1 when application is I/O bound
# Note: need to find the best value based on your performance test result when nio.server.BizExecutor.mode=Mixed
#gRpc.server.pool.BizExecutor.mode=VirtualThread

# Note: coreSize 0 = current computer/VM's available processors x 2 + 1
gRpc.server.pool.coreSize=0

# Note: maxSize 0 = current computer/VM's available processors x 2 + 1
gRpc.server.pool.maxSize=0

# Note: The waiting list size when the pool is full
#gRpc.server.pool.queueSize=2147483647
#gRpc.server.pool.keepAliveSeconds=60
#gRpc.server.pool.prestartAllCoreThreads=false
#gRpc.server.pool.allowCoreThreadTimeOut=false


###########################
# 2. gRpc.server keystore #
###########################
# Note: Path to key store file. Use SSL/TLS when keystore is provided, otherwise use plain socket
gRpc.server.ssl.KeyStore=keystore.p12
gRpc.server.ssl.KeyStorePwd=ENC(FL1BmajTC9w3xaaqhcICrNOawK1VEBnQi0LV9jSNXRHMa0XT7csfASCAtRKiPC7tPhEnuQ==)
gRpc.server.ssl.KeyAlias=server2_4096.jexpress.org
gRpc.server.ssl.KeyPwd=ENC(SJwjOmxQ3rsbB5tICVg8crqo81EvWEFvysYdMy9vfODOfmx05qQs+Wy5pOtPkzRNEwpR4w==)


#############################
# 3. gRpc.server truststore #
#############################
# Note: Path to trust store file. Two-Way SSL (Client-Auth required) when specified, otherwise One-Way SSL (Client-Auth not required)
#gRpc.server.ssl.TrustStore=truststore_grpc_server.p12
#gRpc.server.ssl.TrustStorePwd=DEC(changeit)
