####################
# 1. Secret things #
####################
#secret.licenseKey==2
#secret.licenseKey=1
secret.licenseKey=ENC(HHuJq206X25cvrXqcZcJmNK7MzGF/3a2kEbS4n+GEI8GGunnGJGcs1C0KBqLyCkX4z6HxZ8GmB16lGw9KSjF7YLbhcmTLiK3YMGfmmFPfpoy0MOysNliwAjHhqv4O01aZKQpIwon+lF2TIxtR3iXEGvrTNswfaeIRJbWWtUhylU3+CEUyJCSdLaTfkB6qnAYg6ZLO2sON+GRDXOjOWRfcbixG0YqKAI=)


############
# 2. Timer #
############
#scheduler.cronExpressions=0 */10 * ? * *;0 0 12 ? * FRI
#idle.hresholdSecond=7
