#########################
# My Header description #
#########################
#plugin.licenseKey=DEC(plain text inside this DEC() will be automatically encrypted by app root password when the application starts or is running)
#plugin.name=
