####################
# 1. Secret things #
####################
secret.licenseKey=ENC(UMddZWAPMk8pLNZQS47Jg11LHnityBxnOwNoErMNUi3NXgw87edRIjVR/jzaXvX/RIkm9JCoOUUEgESZl3TodmFlIBeur/HaLR6/MCUgi7oPHJeHHEpZIdXb1SeY57Z5KC6padgVfRpFv8k3595AxZQt8m/iIyua5iAvcWAJnsJ7xUmhxcdikhUZyrJuxVtQeBS1iPhCs3VYA8wdwR40rNoLf5xmESg=)


############
# 2. Timer #
############
#scheduler.cronExpressions=0 */10 * ? * *;0 0 12 ? * FRI
#idle.hresholdSecond=7
