#######################################
# 1. MQTT.client server endpoint      #
# protocol: tcp/ssl/local/ws/wss      #
# [Format] protocol://servername:port #
# [Example] ssl://localhost:8883      #
#######################################
MQTT.client.serverURI=ssl://localhost:8883

# Note: Valid values: TLSv1.2, TLSv1.3. Use plaintext socket no SSL/TLS when specified as blank
#MQTT.client.ssl.Protocol=TLSv1.3


###########################
# 2. MQTT.client keystore #
###########################
# Note: Path to key store file. Use JDK default keystore when not specified
MQTT.client.ssl.KeyStore=keystore.p12
MQTT.client.ssl.KeyStorePwd=ENC(4SOEF5hNHppxCpvogaoqG+D8aVqG9D8787FL2zoMiO6hoLvmLUoxgf+C/19LhwZhO53+Ig==)
MQTT.client.ssl.KeyAlias=server1_2048.jexpress.org
MQTT.client.ssl.KeyPwd=ENC(F4vylHg3Qd87Z4XHmmN/OitcKsakPnQhbXk+CSr76cirptNZRFn72/khFSM6tT99yTIiPQ==)


#############################
# 3. MQTT.client truststore #
#############################
# Note: Path to trust store file. Use JDK default truststore when not specified
MQTT.client.ssl.TrustStore=truststore_mqtt_client.p12
MQTT.client.ssl.TrustStorePwd=ENC(i4qONhF51u32g9ouRq3rt3d1CZscDhy8xfr2Nl2vJZRzikWBsaH7NJ2AeoKZprHg63O6YQ==)
#MQTT.client.VerifyHostname=true


##################################
# 4. MQTT.client user credential #
##################################
#MQTT.client.clientId=
#MQTT.client.username=
#MQTT.client.password=DEC(plain text inside this DEC() will be automatically encrypted by app root password when the application starts or is running)


############################
# 5. MQTT.client messaging #
############################
# Note: 0=At most once, Fire-and-Forget (QoS 0), 1=At least once (QoS 1), 2=Exactly once (QoS 2)
#MQTT.client.defaultQoS=2


###############################
# 6. MQTT.client pub settings #
###############################
#MQTT.client.CleanStart=true
#MQTT.client.Retain=true
#MQTT.client.Topic=
