####################
# 1. Secret things #
####################
secret.licenseKey=ENC(ESrKp+SWqEkxhnxkAd7gtqREj6g3PmQMUI0eBbTiL3zKxc/04NW2XBVNEdWJGecDqxM2Gs/l5vTsLEugwSgQeh4ma+aJYQUSBz5xs5DXfRclEsH/c6zleLB927SbJBQV0/T0ru9M15KpXNSZv+sPtQRqAqJhelAlDG2/N/XLGu3kywczsivTC2KhUh6l9SaXkZNqZfOGEdn1eEeDTPbLZ+svzoBp9A4=)


############
# 2. Timer #
############
#scheduler.cronExpressions=0 */10 * ? * *;0 0 12 ? * FRI
#idle.hresholdSecond=7
