#######################################
# 1. MQTT.client server endpoint      #
# protocol: tcp/ssl/local/ws/wss      #
# [Format] protocol://servername:port #
# [Example] ssl://localhost:8883      #
#######################################
MQTT.client.serverURI=ssl://localhost:8883

# Note: Valid values: TLSv1.2, TLSv1.3. Use plaintext socket no SSL/TLS when specified as blank
#MQTT.client.ssl.Protocol=TLSv1.3


###########################
# 2. MQTT.client keystore #
###########################
# Note: Path to key store file. Use JDK default keystore when not specified
MQTT.client.ssl.KeyStore=keystore.p12
MQTT.client.ssl.KeyStorePwd=ENC(13XmG+OS7kEQKAYR/djzpIJCug+Pf1CeV92CZF1eHcaMebPQeUsn2H77QOa/HkBTSqWbCg==)
MQTT.client.ssl.KeyAlias=server1_2048.jexpress.org
MQTT.client.ssl.KeyPwd=ENC(Xmkn2M86o+NYKkYt2YjmNT/Ox+dmE9ACmOQbG+cy+P1PsqV9Mmzntqq0uOyye3Ob1VAZRA==)


#############################
# 3. MQTT.client truststore #
#############################
# Note: Path to trust store file. Use JDK default truststore when not specified
MQTT.client.ssl.TrustStore=truststore_mqtt_client.p12
MQTT.client.ssl.TrustStorePwd=ENC(DXgFt7UNR27pVSGMVhrAx/oRbd5STWtEKL7YBOnOOzIICcZVX50d/Z1Jvz4/2egEvtaTqA==)
#MQTT.client.VerifyHostname=true


##################################
# 4. MQTT.client user credential #
##################################
#MQTT.client.clientId=
#MQTT.client.username=
#MQTT.client.password=DEC(plain text inside this DEC() will be automatically encrypted by app root password when the application starts or is running)


############################
# 5. MQTT.client messaging #
############################
# Note: 0=At most once, Fire-and-Forget (QoS 0), 1=At least once (QoS 1), 2=Exactly once (QoS 2)
#MQTT.client.defaultQoS=2


###############################
# 6. MQTT.client pub settings #
###############################
#MQTT.client.CleanStart=true
#MQTT.client.Retain=true
#MQTT.client.Topic=
