#############################################################
# 1. NIO Network Listeners                                  #
# [Format] ip1:port1, ip2:port2, ..., ipN:portN             #
# [Example] 192.168.1.10:8311, 127.0.0.1:8311, 0.0.0.0:8311 #
#############################################################
nio.server.bindings=0.0.0.0:8211, 0.0.0.0:8311
#nio.server.autostart=true

# Note: make it prime number when you have both NIO and gRPC server running
#nio.server.idle.threshold.second=61

# Note: @Inspector.names in CSV format, empty/null means require ALL HealthChecks
#ping.sync.HealthStatus.requiredHealthChecks=

# Note: Ping response status is synced with PAUSE status
#ping.sync.PauseStatus=true

# Note: Ping response with root cause, this may expose internal info to external caller
#ping.sync.showRootCause=false


##########################
# 2.1 NIO Security - TLS #
##########################
# Note: Path to key store file. Required when TLS protocol is not blank or not empty
nio.server.ssl.KeyStore=keystore.p12
nio.server.ssl.KeyStorePwd=ENC(IoZ59Ncy+umy/so9cMzaOgG56Plv/qb2qVoamhPH0w9Ti3IretUC4TZHf1V3uKC/BYWf8Q==)
nio.server.ssl.KeyAlias=server1_2048.jexpress.org
nio.server.ssl.KeyPwd=ENC(g0axqaBQfZ6vX5jvLEc3y+qoUXy3+RQjjsHMKR4QWx4kWyBIU4IJmn6OTBYrVYfWibhZ6Q==)

# Note: Path to trust store file. Two-Way SSL (Client-Auth required) when specified, otherwise One-Way SSL (Client-Auth not required)
#nio.server.ssl.TrustStore=
#nio.server.ssl.TrustStorePwd=DEC(plain text inside this DEC() will be automatically encrypted by app root password when the application starts or is running)
#nio.server.ssl.VerifyCertificateHost=false
#nio.server.ssl.Provider=OPENSSL

# Note: Valid values: TLSv1.2, TLSv1.3. Use plaintext socket no SSL/TLS when specified as blank
#nio.server.ssl.Protocols=TLSv1.2, TLSv1.3

# Note: use system default cipher suites when not specified
#nio.server.ssl.CipherSuites=


#############################
# 2.2 NIO Security - Filter #
#############################
# Note: Filters the caller's network address by type.
# Note: Accepted values: String, HostString, HostName, AddressString, HostAddress, AddrHostName, or CanonicalHostName
#filter.CallerAddress.option=String

# Note: Caller network addr whitelist in CSV format, example: 127.0.0.1, 192\\.168\\.1\\.
#filter.CallerAddress.Whitelist=

# Note: Caller network addr blacklist in CSV format, example: 10.1.1.40, 192\\.168\\.2\\.
#filter.CallerAddress.Blacklist=

# Note: Http Request whitelist in CSV format
# [Format] CSV of regex patterns targeting Method/Path
# [Example] ^POST/myservice1/.* , /service1/action1/ , /service1/action2
#filter.Request.Whitelist=

# Note: Http Request blacklist in CSV format
# [Format] CSV of regex patterns targeting Method/Path
# [Example] ^POST/myservice2/.* , ^DELETE/service2/action1/ , /service2/action2
#filter.Request.Blacklist=


#########################
# 3.1 Socket controller #
#########################
#nio.server.socket.SO_REUSEADDR=true
#nio.server.socket.SO_KEEPALIVE=true
#nio.server.socket.TCP_NODELAY=true
#nio.server.socket.SO_LINGER=-1


##########################
# 3.2 Socket Performance #
##########################
#nio.server.ssl.HandshakeTimeout.second=30
#nio.server.socket.CONNECT_TIMEOUT.second=30
#nio.server.socket.SO_BACKLOG=1024

# Note: cat /proc/sys/net/ipv4/tcp_rmem (max 1024k)
#nio.server.socket.SO_RCVBUF=1048576

# Note: cat /proc/sys/net/ipv4/tcp_smem (max 1024k)
#nio.server.socket.SO_SNDBUF=1048576

# Note: default - 64kb
#nio.server.HttpObjectAggregator.maxContentLength=65536


########################
# 4.1 Netty controller #
########################
#nio.server.multiplexer=AVAILABLE
#nio.server.httpServerCodec.MaxInitialLineLength=8192
#nio.server.httpServerCodec.MaxHeaderSize=8192
#nio.server.httpServerCodec.MaxChunkSize=8192


#####################################################
# 4.2 Netty Performance - NIO and Biz Executor Pool #
#####################################################
#nio.server.EventLoopGroup.Acceptor.useVirtualThread=false

# Note: AcceptorSize 0 = number of bindings
#nio.server.EventLoopGroup.AcceptorSize=0
#nio.server.EventLoopGroup.Worker.useVirtualThread=false

# Note: WorkerSize 0 = current computer/VM's available processors x 2 + 1
nio.server.EventLoopGroup.WorkerSize=0

# Note: valid value = VirtualThread (default for Java 21+), CPU, IO and Mixed (default for old Java)
# Note: use CPU core + 1 when application is CPU bound
# Note: use CPU core x 2 + 1 when application is I/O bound
# Note: need to find the best value based on your performance test result when nio.server.BizExecutor.mode=Mixed
#nio.server.BizExecutor.mode=VirtualThread

# Note: CoreSize 0 = current computer/VM's available processors x 2 + 1
nio.server.BizExecutor.CoreSize=0

# Note: MaxSize 0 = current computer/VM's available processors x 2 + 1
nio.server.BizExecutor.MaxSize=0
#nio.server.BizExecutor.KeepAliveSec=60

# Note: The waiting list size when the pool is full
#nio.server.BizExecutor.QueueSize=2147483647
#nio.server.BizExecutor.prestartAllCoreThreads=false
#nio.server.BizExecutor.allowCoreThreadTimeOut=false
#nio.server.BizExecutor.bizTimeoutWarnThresholdMs=5000


#############################
# 4.3 Netty Channel Handler #
#############################
# Note: rec Idle enabled only when value > 0
#nio.server.ReaderIdleSeconds=0

# Note: Sent Idle enabled only when value > 0
#nio.server.WriterIdleSeconds=0
#nio.server.health.InspectionIntervalSeconds=5
#nio.WebSocket.Compress=true

# Note: Indicates the maximum number of bytes allowed to be allocated when a single WebSocket data frame is compressed (or decompressed). It is used to limit the maximum memory allocation during the compression process.
#nio.WebSocket.Compress.maxAllocation=0
#nio.WebSocket.AllowExtensions=true
#nio.WebSocket.maxFrameSize=5242880
#nio.WebSocket.AllowMaskMismatch=false
#nio.WebSocket.CheckStartsWith=false
#nio.WebSocket.DropPongFrames=true
#nio.WebSocket.HandshakeTimeoutMs=10000


##########################
# 4.4. Request/Response  #
##########################
#nio.JAX-RS.fromJson.CaseInsensitive=false
#nio.JAX-RS.fromJson.failOnUnknownProperties=true
#nio.JAX-RS.fromJson.autoBeanValidation=true
#nio.JAX-RS.toJson.IgnoreNull=true
#nio.JAX-RS.toJson.IgnoreEmptyArray=false
#nio.JAX-RS.toJson.Pretty=false
#nio.JAX-RS.toJson.showRefInServiceError=true

# Note: The ID for a TimeZone, either an abbreviation such as "UTC", a full name such as "America/Toronto", or a custom ID such as "GMT-8:00", or "system" as system default timezone.
#nio.JAX-RS.jsonParser.TimeZone=system

# Note: Accept-Charset header is deprecated and no longer used by modern browsers,
# Note: servers often default to a widely compatible encoding UTF-8 (for English/French only, like Canada set it to ISO-8859-1) or the resource's default encoding for better user experience.
#nio.default.response.Charset=UTF-8


######################################
# 5. IO Communication logging filter #
######################################
# Note: 5.1 caller filter
# Note: valid value = id, uid, group, role, ignore
#nio.verbose.filter.usertype=ignore

# Note: user range (when type=CallerId): N1 - N2 or N1, N2, ... , Nn
# Note: user range (when type=CallerName): johndoe, janedoe
#nio.verbose.filter.usertype.range=

# Note: valid value = HttpStatusCode, ApplicationErrorCode, all, ignore
#nio.verbose.filter.codetype=all

# Note: 5.2 error code filter
# Note: code range: N1 - N2 or N1, N2, ... , Nn
#nio.verbose.filter.codetype.range=
#nio.verbose.aspect.ReqHeader=true
#nio.verbose.aspect.ReqContent=true
#nio.verbose.aspect.RespHeader=true
#nio.verbose.aspect.RespContent=true


#########################
# 6. POI logging filter #
#########################
# Note: valid value = filter, all, ignore
#nio.verbose.ServiceTimePOI.type=all

# Note: CSV format
#nio.verbose.ServiceTimePOI.filter=auth.begin, auth.end, db.begin, db.end


######################
# 7. Web Server Mode #
######################
#server.http.web.docroot=docroot
#server.http.web.docroot.errorPageFolderName=errorpages
#server.http.web.welcomePage=index.html
#server.http.web-server.tempupload=temp/upload


####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
# 8. Default Server Response HTTP Headers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #
# put generic HTTP response headers here                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #
# [Format] server.DefaultResponseHttpHeaders.<response_header_name>=<response_header_value>                                                                                                                                                                                                                                                                                                                                                                                                                                                        #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Allow-Origin=https://www.summerboot.org                                                                                                                                                                                                                                                                                                                                                                                                                                               #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Allow-Headers=X-Requested-With, Content-Type, Origin, Authorization                                                                                                                                                                                                                                                                                                                                                                                                                   #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Allow-Methods=PUT,GET,POST,DELETE,OPTIONS,PATCH                                                                                                                                                                                                                                                                                                                                                                                                                                       #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Allow-Credentials=false                                                                                                                                                                                                                                                                                                                                                                                                                                                               #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Allow-Credentials=false                                                                                                                                                                                                                                                                                                                                                                                                                                                               #
# [Example] server.DefaultResponseHttpHeaders.Access-Control-Max-Age=3600                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #
# [Example] server.DefaultResponseHttpHeaders.Content-Security-Policy=default-src 'self';script-src 'self' www.google-analytics.com www.google.com www.gstatic. js.stripe.com ajax.cloudflare.com;style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com;img-src 'self' www.google-analytics.com stats.g.doubleclick.net www.gstatic.com;font-src 'self' cdnjs.cloudflare.com fonts.gstatic.com;base-uri 'self';child-src www.google.com js.stripe.com;form-action 'self';frame-ancestors 'none';report-uri="https://www.summerboot.org/report-uri" #
# [Example] server.DefaultResponseHttpHeaders.X-XSS-Protection=1; mode=block                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #
# [Example] server.DefaultResponseHttpHeaders.Strict-Transport-Security=max-age=31536000;includeSubDomains;preload                                                                                                                                                                                                                                                                                                                                                                                                                                 #
# [Example] server.DefaultResponseHttpHeaders.X-Frame-Options=sameorigin                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #
# [Example] server.DefaultResponseHttpHeaders.Expect-CT=max-age=86400, enforce, report-uri="https://www.summerboot.org/report-uri"                                                                                                                                                                                                                                                                                                                                                                                                                 #
# [Example] server.DefaultResponseHttpHeaders.X-Content-Type-Options=nosniff                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #
# [Example] server.DefaultResponseHttpHeaders.Feature-Policy=autoplay 'none';camera 'none'                                                                                                                                                                                                                                                                                                                                                                                                                                                         #
####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
#server.DefaultResponseHttpHeaders.response_header_name=response_header_value
