####################
# 1. Secret things #
####################
secret.licenseKey=ENC(3tWARON+jH1dc9ifGrZ0zTCCnZcS1IgaPK/QWLovRICV45XT185EPlvUqOkyhPyS+wVam/chotul5e6FuSti6Y0c6yytJw+xt37cm23nQadq4h9VOHpGiKhzqePFl0c489PUBa0HKffGHH6OEbz1bkDB5sVZ/kMcAJEfnB8lHdbzfEUDtEgdK9Ki6WM+IztcvKa7sXfcDLFYdJFEOGvIo369)


############
# 2. Timer #
############
#scheduler.cronExpressions=0 */10 * ? * *;0 0 12 ? * FRI
#idle.hresholdSecond=7
